# Generated by Django 4.1.3 on 2022-12-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_userprofile_alter_userinfo_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salt',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.userprofile'),
        ),
    ]
