# Generated by Django 4.1.3 on 2022-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_remove_userprofile_salt_alter_userinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='passhash',
            new_name='password',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
